// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TEMPORARY WORKAROUND: Hardcoded credentials due to env var loading issue
// TODO: Remove this once Lovable Support fixes Cloud environment variable provisioning
const SUPABASE_URL = "https://fhvgadhwousdtizagedn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodmdhZGh3b3VzZHRpemFnZWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2ODU1NTAsImV4cCI6MjA3NTI2MTU1MH0.x7UQ0JvZ88HDJOjE65Vr87Ie5bw-jr7mUf3bXtEswOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});